version: '3'

services:

  php:
    build: ./docker/php
    volumes:
      - ./project:/project
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db

  db:
    image: mariadb:10.3.30-focal
    restart: always
    environment:
      MARIADB_DATABASE: 'mydb'
      MARIADB_ROOT_PASSWORD: 'toor'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'userpasswd'
      TZ: Europe/Prague
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/local.cnf
      - ./data/db:/var/lib/mysql
    ports:
      - '3306:3306'
